id: I2CEE9157
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T13:08:28.123015'
last_modified: '2022-06-19T13:08:28.123177'
parser: null
source_metadata:
  title: Hagiography of Ngor chen Kun dga bzang po (1382-1456), no. III; Lamdre Lobshe,
    vol. ka, title no. 23
  author: དགེ་སློང་དཔལ་ལྡན་དོན་གྲུབ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-08-19);
    converted from external file, unrevised, spell-checked, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), Kunga Dorje (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/376
  bases:
    0e42:
      title: Hagiography of Ngor chen Kun dga bzang po (1382-1456), no. III; Lamdre
        Lobshe, vol. ka, title no. 23
      order: 1
      base_file: 0e42.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
